export type Product = {
  id: number;
  title: string;
  category: string;
  brand: string;
  image: string;
  rating: number;
  reviews: number;
  cps: string;
  discount: string;
  price: number;
  oldPrice: number;
  description: string;
  features: string[];
};

export const products: Product[] = [
  {
    id: 1,
    title: "Amazon UAE Electronics Deal",
    category: "Electronics",
    brand: "Amazon",
    image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 128,
    cps: "7.20% CPS",
    discount: "-20%",
    price: 4200,
    oldPrice: 5250,
    description: "Premium electronics affiliate deal with full product details inside NRDealHub.",
    features: ["Fast product access", "Verified deal", "Best for electronics buyers"],
  },
  {
    id: 2,
    title: "Under Armour Sports Offer",
    category: "Sports",
    brand: "Under Armour",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 96,
    cps: "6.40% CPS",
    discount: "-15%",
    price: 3500,
    oldPrice: 4100,
    description: "Sports shoe and accessories offer with local checkout support.",
    features: ["Sports category", "High quality product", "Easy checkout"],
  },
  {
    id: 3,
    title: "Nike Style Shoe Coupon",
    category: "Fashion",
    brand: "Nike",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 76,
    cps: "4.80% CPS",
    discount: "-10%",
    price: 5200,
    oldPrice: 5800,
    description: "Fashion shoe coupon shown fully inside NRDealHub. No external signup required.",
    features: ["Fashion product", "Modern design", "Buy from our site flow"],
  },
  {
    id: 4,
    title: "Kaspersky Digital Security",
    category: "Digital Services",
    brand: "Kaspersky",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 112,
    cps: "30% CPS",
    discount: "-25%",
    price: 1900,
    oldPrice: 2500,
    description: "Digital security service deal with simple purchase flow.",
    features: ["Digital service", "Security software", "Instant order request"],
  },
  {
    id: 5,
    title: "Noon Marketplace Deal",
    category: "Marketplace",
    brand: "Noon",
    image: "https://images.unsplash.com/photo-1607083206968-13611e3d76db?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 144,
    cps: "5.50% CPS",
    discount: "-18%",
    price: 2800,
    oldPrice: 3400,
    description: "Marketplace deal with product details and own-site checkout.",
    features: ["Marketplace product", "Special discount", "Cart supported"],
  },
  {
    id: 6,
    title: "AliExpress Gadget Deal",
    category: "Marketplace",
    brand: "AliExpress",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80",
    rating: 4,
    reviews: 221,
    cps: "8.00% CPS",
    discount: "-30%",
    price: 1500,
    oldPrice: 2150,
    description: "Gadget deal displayed on NRDealHub with own cart and checkout.",
    features: ["Gadget product", "Budget friendly", "Order success page"],
  },
  {
    id: 7,
    title: "Daraz BD Product Deal",
    category: "Marketplace",
    brand: "Daraz",
    image: "https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 89,
    cps: "6.00% CPS",
    discount: "-22%",
    price: 2300,
    oldPrice: 2950,
    description: "Bangladesh friendly product deal with local checkout experience.",
    features: ["BD friendly", "Easy order", "Product details page"],
  },
  {
    id: 8,
    title: "Hosting Premium Deal",
    category: "Web Hosting",
    brand: "Hosting",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 64,
    cps: "45% CPS",
    discount: "-50%",
    price: 2999,
    oldPrice: 5999,
    description: "Hosting deal with details, cart and order confirmation.",
    features: ["Web hosting", "High CPS", "Digital order"],
  },
  {
    id: 9,
    title: "VPN Privacy Deal",
    category: "Digital Services",
    brand: "VPN",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=80",
    rating: 4,
    reviews: 58,
    cps: "35% CPS",
    discount: "-40%",
    price: 1700,
    oldPrice: 2800,
    description: "VPN privacy service deal with own-site checkout flow.",
    features: ["Privacy service", "Digital product", "Secure order"],
  },
  {
    id: 10,
    title: "Mobile Accessories Deal",
    category: "Electronics",
    brand: "Accessories",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 172,
    cps: "9.20% CPS",
    discount: "-28%",
    price: 999,
    oldPrice: 1390,
    description: "Mobile accessories product with cart and checkout support.",
    features: ["Mobile accessory", "Low price", "Popular product"],
  },
  {
    id: 11,
    title: "Fashion Coupon Deal",
    category: "Fashion",
    brand: "Fashion",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 103,
    cps: "7.50% CPS",
    discount: "-35%",
    price: 1800,
    oldPrice: 2770,
    description: "Fashion coupon deal with complete details in NRDealHub.",
    features: ["Fashion item", "Discount coupon", "Easy checkout"],
  },
  {
    id: 12,
    title: "Electronics Coupon",
    category: "Electronics",
    brand: "Electronics",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80",
    rating: 5,
    reviews: 190,
    cps: "10% CPS",
    discount: "-32%",
    price: 4500,
    oldPrice: 6600,
    description: "Electronics coupon product with order success inside your site.",
    features: ["Electronics", "Coupon supported", "Best value"],
  },
];

export function getProductById(id: string | number) {
  return products.find((product) => product.id === Number(id));
}
